### ISSUE TITLE
疑问:在编译的时候.gold文件有什么用

### ISSUE THREAD

**Issue by ZhiquanW** [depctg/udacity-cs344-colab#1]
![image](https://user-images.githubusercontent.com/22308667/56143894-f8e4e780-5fd3-11e9-8db5-311da68874b5.png)
请问第四行命令有什么用

**Comment by depctg** [comment]
运行编译出来的binary并和标准文件比较

Zhiquan.Wang <notifications@github.com>于2019年4月15日 周一23:13写道：

**Comment by ZhiquanW** [comment]
还是不是很明确, 请问你指的标准文件是reference的图片吗? 运行的是哪一个文件呢?

**Comment by depctg** [comment]
运行的是bin/HW1文件，这个是第一行的make命令生成的文件。
gold相当于输入的源文件，如果用binary editor打开你会发现它是一张png）输入之后会用标准算法和你的算法分别处理再进行对比。所以你可以替换这个文件名来处理自己的图片。
不带参数运行 bin/HW1 可以看到各个参数的含义。

**Comment by ZhiquanW** [comment]
明白了 感谢!
