### ISSUE TITLE
Unsupported gpu architecture 'compute_30'

### ISSUE THREAD

**Issue by JavidanAbdullayev** [depctg/udacity-cs344-colab#3]
When I run the cell **# make the cuda project** of the colab notebook **udacity-cs344-hw1**  I faced such an error as below.  Could you help me?

`
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at HW1_generated_student_func.cu.o.cmake:222 (message):
  Error generating
  /content/udacity-cs344-colab/build/HW1/CMakeFiles/HW1.dir//./HW1_generated_student_func.cu.o

HW1/CMakeFiles/HW1.dir/build.make:63: recipe for target 'HW1/CMakeFiles/HW1.dir/HW1_generated_student_func.cu.o' failed
make[3]: *** [HW1/CMakeFiles/HW1.dir/HW1_generated_student_func.cu.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'HW1/CMakeFiles/HW1.dir/all' failed
make[2]: *** [HW1/CMakeFiles/HW1.dir/all] Error 2
CMakeFiles/Makefile2:102: recipe for target 'HW1/CMakeFiles/HW1.dir/rule' failed
make[1]: *** [HW1/CMakeFiles/HW1.dir/rule] Error 2
Makefile:118: recipe for target 'HW1' failed
make: *** [HW1] Error 2

====== RESULT OF HW1 =======

/bin/bash: bin/HW1: No such file or directory`

**Comment by FormalIngenieroniel** [comment]
Same here, have you found something yet? Best wishes
